title: kahteik।
description: A simple website that serves a simple purpose. kahteik knows italiano, español, русский алфавит, देवनागरी and 한글.
github.owner_url: https://github.com/bernardkkt
theme: jekyll-theme-minimal
