title: kahteik।
description: A simple website that serves a simple purpose. kahteik knows italiano, español, русский алфавит, देवनागरी and 한글.
lang: en-GB
owner_url: https://github.com/bernardkkt
show_project_lists: true
theme: jekyll-theme-minimal
